
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'test'
      shell: bash
      run: |
         ls -la 
         pwd
         cd ..
         ls -la
         cd devops_todo
         ls -la
