
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout task branch
      uses: actions/checkout@v4
    - name: 'test'
      shell: bash
      run: |
         ls -la 
         pwd
        
