
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'test'
      working-directory: ./app
      shell: bash
      run: |
         ls -la 
         pwd
        
